### ISSUE TITLE
parks.geojson has gone missing

### ISSUE THREAD

**Issue by joel6653** [friendlycode/grparks#43]
Some time in the day or day-and-a-half, the parks.geojson file used to drive the front-end interface, has gone missing. It may or may not be related to the difficulties that @MuellerL has had getting Parks & Rec staff the proper permissions and procedures to publish new millage.csv data.

**Comment by jacebrowning** [comment]
The first cue for me is that the build is now failing: https://travis-ci.org/friendlycode/grparks

**Comment by jacebrowning** [comment]
Inspecting the logic, it seems that we were still uploading files to GitHub even when parks were missing. This should fix that: https://github.com/friendlycode/grparks/pull/44

**Comment by jacebrowning** [comment]
@joel6653 @MuellerL I believe that if you remove those six offending parks form the CSV on the data portal or add/rename them on OSM it will start working again.

**Comment by joel6653** [comment]
These are new-to-the-list parks that we thought Karie could simply add to the .csv file, and then @MuellerL  and/or I could follow up by making sure they get into OSM. We had no idea, of course, that it would break everything. Any way of preventing the break from happening the next time?

**Comment by jacebrowning** [comment]
> preventing the break from happening
What would you like to happen when new, unknown parks are added?

**Comment by joel6653** [comment]
It could just skip that park in the processing, and proceed to publish the remaining good ones. That way, when Karie or whoever adds a park to the .csv file, and then notices the next day that it still isn't shown in the interface, somebody can take action to add it to OSM. Much better than breaking everything. Possible?
